### ISSUE TITLE
[UI][alias] display alias for address

### ISSUE THREAD

**Issue by rueshyna** [marigold-dev/tzsafe-ui#106]
from @aguillon 
> I like that I can just transfer a token to a multisig from my wallet and that it appears in the history with the name I gave at the multisig creation and not my account address. However, in the future we're going to have people managing tokens with various external contracts (e.g., Youves vaults) and all they're going to read is KT1somethingsomething. We should start thinking about extending aliases now, for instance by using [the same aliases as tzkt](https://baking-bad.org/blog/2021/09/19/tzkt-alias-verification-f-a-q/). This isn't urgent, but I'm curious about your take on this.

There are few tasks about alias in the backlog. We'll go back for this in near future.

**Comment by oteku** [comment]
Rules to apply by priority:

1. Replace KT1 address by TzSafe "Wallet name", if the address is in the wallet list of the connected account
2. Get alias from Tzkt API https://api.tzkt.io/#operation/Accounts_Get
3. Display adress as is
