### ISSUE TITLE
[UI][Feature] signing and resolving proposal together with creating proposal

### ISSUE THREAD

**Issue by rueshyna** [marigold-dev/tzsafe-ui#150]
Current state: 
- When a proposal is created, it will display on the proposal page with signing and "Try to resolve immediately " option.

![image](https://github.com/marigold-dev/tzsafe-ui/assets/115862/2d622112-df70-4dff-b491-dded05c3bf44)

Change: 
- When a proposal is creating, display the checkbox "Sign immediately" with default check
- If the threshold of the proposal is 1 and the checkbox of "sign immediately" is checked, display another checkbox "Resolve immediately"

Notice that there are two ways of creating proposal:
- from the new proposal page by users
- through beacon connection by dapps

**Comment by Pilou97** [comment]
closing the issues since https://github.com/marigold-dev/tzsafe-ui/pull/161 is merged
