### ISSUE TITLE
[UX] improve state management

### ISSUE THREAD

**Issue by oteku** [marigold-dev/tzsafe-ui#168]
Whenever you display a Safe, next time you go to tzsafe.marigold.dev, you access last wallet you accessed. It is disturbing cause it can be a safe you are not in (you displayed a random wallet, or you connect with multiple accpount to the app.

Expected behavior:  tzsafe.marigold.dev routes to the first wallet in you imported wallet list or to new wallet page if you have none.

⚠️ test with multiple account using the same browser

**Comment by oteku** [comment]
This feature requires to be able to edit wallet name. We could have a text pointer cursor when cursor is over the name and have edit when we click on, save on clic out.

<img width="274" alt="pointer" src="https://github.com/marigold-dev/tzsafe-ui/assets/5846502/fc8dd84d-f2ca-470a-a004-34a3342050ea">

**Comment by quentin-burg** [comment]
Closed with https://github.com/marigold-dev/tzsafe-ui/pull/172
